server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-discovery:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/join
            - Method=POST
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/login
            - Method=POST
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
            - name: JwtFilter
              args:
                preLogger: true
                postLogger: true

        - id: pt-service
          uri: lb://PT-SERVICE
          predicates:
            - Path=/pt/**
          filters:
            - RewritePath=/pt/(?<segment>.*), /$\{segment}
            - name: JwtFilter
              args:
                preLogger: true
                postLogger: true

        - id: community-service
          uri: lb://COMMUNITY-SERVICE
          predicates:
            - Path=/community/**
          filters:
            - RewritePath=/community/(?<segment>.*), /$\{segment}
            - name: JwtFilter
              args:
                preLogger: true
                postLogger: true

jwt:
  secret: ${JWT_SECRET}
