server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_URL}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/join
            - Method=POST
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/login
            - Method=POST
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}

        # 스웨거
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/v3/api-docs
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
            - name: JwtFilter
              args:
                preLogger: true
                postLogger: true

        # 스웨거
        - id: pt-service
          uri: lb://PT-SERVICE
          predicates:
            - Path=/pt/v3/api-docs
          filters:
            - RewritePath=/pt/(?<segment>.*), /$\{segment}

        - id: pt-service
          uri: lb://PT-SERVICE
          predicates:
            - Path=/pt/**
          filters:
            - RewritePath=/pt/(?<segment>.*), /$\{segment}
            - name: JwtFilter
              args:
                preLogger: true
                postLogger: true

        # 스웨거
        - id: community-service
          uri: lb://COMMUNITY-SERVICE
          predicates:
            - Path=/community/v3/api-docs
          filters:
            - RewritePath=/community/(?<segment>.*), /$\{segment}

        - id: community-service
          uri: lb://COMMUNITY-SERVICE
          predicates:
            - Path=/community/**
          filters:
            - RewritePath=/community/(?<segment>.*), /$\{segment}
            - name: JwtFilter
              args:
                preLogger: true
                postLogger: true

jwt:
  secret: ${JWT_SECRET}

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /auth/v3/api-docs
      - name: pt-service
        url: /pt/v3/api-docs
      - name: community-service
        url: /community/v3/api-docs
    use-root-path: true
